export const RECIPES_ACTION_TYPES = {
    SET_RECENTLY_VIEWED: 'SET_RECENTLY_VIEWED',
    SET_RECENTLY_ADDED: 'SET_RECENTLY_ADDED',
    SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',
    SET_RECIPE_BY_ID: 'SET_RECIPE_BY_ID',
    ADD_RECIPE: 'ADD_RECIPE',
    UPDATE_RECIPE: 'UPDATE_RECIPE',
    DELETE_RECIPE: 'DELETE_RECIPE',
    SEARCH_RECIPES: 'SEARCH_RECIPES'
}